SIMBION20/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_utama.urls as halaman_utama
import login.urls as login
import register.urls as register
import daftarbeasiswa.urls as daftarbeasiswa


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(halaman_utama, namespace='halaman_utama')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^register/', include(register, namespace='register')),
    url(r'^daftarbeasiswa/', include(daftarbeasiswa, namespace='daftarbeasiswa')),
]

daftarbeasiswa/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    #url(r'^$', login, name='login'),
    url(r'^pendaftaranpaket/$', pendaftaranpaket, name='pendaftaranpaket'),
    url(r'^tambahbeasiswa/$', tambahbeasiswa, name='tambahbeasiswa'),
    url(r'^registrasi_paket/$', registrasi_paket, name='registrasi_paket'),
    url(r'^registrasi_beasiswa/$', registrasi_beasiswa, name='registrasi_beasiswa'),
    #url(r'^auth_logout/$', auth_logout, name='auth_logout'),
]

login/urls.py
from django.conf.urls import url
from .views import login
from .custom_auth import auth_login, auth_logout
#url for app
urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout'),
]

daftarbeasiswa/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models

class Pengguna(models.Model):
    username = models.CharField(primary_key=True, max_length=20)
    password = models.CharField(max_length=20)
    role = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pengguna'

class Donatur(models.Model):
    nomor_identitas = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    npwp = models.CharField(max_length=20)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat = models.CharField(max_length=50)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'donatur'

class Admin(models.Model):
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username', primary_key=True)

    class Meta:
        managed = False
        db_table = 'admin'

class IndividualDonor(models.Model):
    nik = models.CharField(primary_key=True, max_length=16)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'individual_donor'

class Yayasan(models.Model):
    no_sk_yayasan = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp_cp = models.CharField(max_length=20, blank=True, null=True)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'yayasan'

class Mahasiswa(models.Model):
    npm = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat_tinggal = models.CharField(max_length=50)
    alamat_domisili = models.CharField(max_length=50)
    nama_bank = models.CharField(max_length=50)
    no_rekening = models.CharField(max_length=20)
    nama_pemilik = models.CharField(max_length=20)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'mahasiswa'

class RiwayatAkademik(models.Model):
    no_urut = models.IntegerField(primary_key=True)
    npm = models.CharField(max_length=20)
    semester = models.CharField(max_length=1)
    tahun_ajaran = models.CharField(max_length=9)
    jumlah_sks = models.IntegerField()
    ips = models.FloatField()
    lampiran = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'riwayat_akademik'
        unique_together = (('no_urut', 'npm'),)

class SkemaBeasiswa(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    jenis = models.CharField(max_length=20)
    deskripsi = models.CharField(max_length=50)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'skema_beasiswa'

class SyaratBeasiswa(models.Model):
    kode_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_beasiswa', primary_key=True)
    syarat = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'syarat_beasiswa'
        unique_together = (('kode_beasiswa', 'syarat'),)

class SkemaBeasiswaAktif(models.Model):
    kode_skema_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_skema_beasiswa', primary_key=True)
    no_urut = models.IntegerField()
    tgl_mulai_pendaftaran = models.DateField()
    tgl_tutup_pendaftaran = models.DateField()
    periode_penerimaan = models.CharField(max_length=50)
    status = models.CharField(max_length=20)
    jumlah_pendaftar = models.IntegerField()
    total_pembayaran = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'skema_beasiswa_aktif'
        unique_together = (('kode_skema_beasiswa', 'no_urut'),)

class Pendaftaran(models.Model):
    no_urut = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='no_urut', primary_key=True)
    kode_skema_beasiswa = models.IntegerField()
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    waktu_daftar = models.DateTimeField()
    status_daftar = models.CharField(max_length=20)
    status_terima = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pendaftaran'
        unique_together = (('no_urut', 'kode_skema_beasiswa', 'npm'),)

class Pembayaran(models.Model):
    urutan = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='kode_skema_beasiswa')
    no_urut_skema_beasiswa_aktif = models.IntegerField()
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    keterangan = models.CharField(max_length=50)
    tgl_bayar = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'pembayaran'
        unique_together = (('urutan', 'kode_skema_beasiswa', 'no_urut_skema_beasiswa_aktif'),)

class TempatWawancara(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    lokasi = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tempat_wawancara'

class Wawancara(models.Model):
    no_urut_skema_beasiswa_aktif = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.ForeignKey(SkemaBeasiswaAktif, models.DO_NOTHING, db_column='kode_skema_beasiswa')
    jadwal = models.DateTimeField()
    kode_tempat_wawancara = models.ForeignKey(TempatWawancara, models.DO_NOTHING, db_column='kode_tempat_wawancara')

    class Meta:
        managed = False
        db_table = 'wawancara'
        unique_together = (('no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'jadwal'),)

class Pengumuman(models.Model):
    tanggal = models.DateField(primary_key=True)
    no_urut_skema_beasiswa_aktif = models.IntegerField()
    kode_skema_beasiswa = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='kode_skema_beasiswa')
    username = models.ForeignKey(Pengguna, models.DO_NOTHING, db_column='username')
    judul = models.CharField(max_length=20)
    isi = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'pengumuman'
        unique_together = (('tanggal', 'no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'username'),)

daftarbeasiswa/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
from halaman_utama.models import *
from halaman_utama.views import dictfetchall

cursor = connection.cursor()

# Create your views here.
def pendaftaranpaket(request):
    response = {}
    return render(request, 'daftarbeasiswa/pendaftaranpaket.html', response)

def tambahbeasiswa(request):
    response = {}
    skemabeasiswa = SkemaBeasiswa.objects.raw('SELECT * FROM skema_beasiswa')
    response["skemabeasiswa"] = skemabeasiswa
    return render(request, 'daftarbeasiswa/tambahbeasiswa.html', response)

def registrasi_paket(request):
	if request.method == "POST":
		kode = request.POST['kode']
		nama_paket = request.POST['nama_paket']
		jenis_paket = request.POST['jenis_paket']
		deskripsi = request.POST['deskripsi']
		syarat_beasiswa = request.POST['syarat_beasiswa']
		cursor.execute('''	INSERT INTO SKEMA_BEASISWA(kode, nama, jenis, deskripsi, nomor_identitas_donatur) 
							VALUES ( %s, %s, %s, %s, '273-53-3379');''', [kode, nama_paket, jenis_paket, deskripsi])
		response = {}
		return HttpResponseRedirect(reverse('halaman_utama:index'))

def registrasi_beasiswa(request):
	if request.method == "POST":
		kodebeasiswa = request.POST['kodebeasiswa']
		no_urut = request.POST['no_urut']
		tanggal_mulai = request.POST['tanggal_mulai']
		tanggal_selesai = request.POST['tanggal_selesai']
		cursor.execute('''	INSERT INTO SKEMA_BEASISWA_AKTIF(kode_skema_beasiswa, no_urut, tgl_mulai_pendaftaran, tgl_tutup_pendaftaran, periode_penerimaan, status, jumlah_pendaftar, total_pembayaran) 
							VALUES ( '%s', %s, %s, %s, 'Sekarang', 'Buka', 0, 0);''', [int(kodebeasiswa), no_urut, tanggal_mulai, tanggal_selesai])
		response = {}
		return HttpResponseRedirect(reverse('halaman_utama:index'))

daftarbeasiswa/templates/daftarbeasiswa/pendaftaranpaket.html
{% extends "halaman_utama/base/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body>
  <div class="py-5 text-white opaque-overlay" style="background-image: url(&quot;https://pingendo.github.io/templates/sections/assets/cover_restaurant.jpg&quot;);">
    <div class="container">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <h1 class="text-gray-dark">Form Pendaftaran Paket Beasiswa</h1>

          <form class="" method="post" action="{% url 'daftarbeasiswa:registrasi_paket' %}">
            {% csrf_token %}
            <div class="form-group">
              <label>Kode</label>
              <input type="text" name="kode" class="form-control" required="required"> </div>
            <div class="form-group">
              <label>Nama Paket Beasiswa</label>
              <input type="text" name="nama_paket" class="form-control" required="required"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Jenis Paket Beasiswa</label>
              <br>
              <div class="btn-group">

                <select id="jenis-paket" name="jenis_paket">
                  <option value="Prestasi Akademik">Beasiswa Prestasi Akademik</option>
                  <option value="Bantuan Belajar"> Beasiswa Bantuan Belajar</option>
                  <option value="Tugas Akhir">Beasiswa Tugas Akhir</option>
                  <option value="Lainnya">Beasiswa Lainnya</option>
                </select>
              </div>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Deskripsi</label>
              <textarea class="form-control" id="exampleTextarea" rows="3" required="required" name="deskripsi"></textarea>
            </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Syarat Beasiswa</label>
              <textarea class="form-control" id="exampleTextarea" rows="3" required="required" name="syarat_beasiswa"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Tambahkan Beasiswa</button>
          </form>

        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

{% endblock %}

daftarbeasiswa/templates/daftarbeasiswa/tambahbeasiswa.html
{% extends "halaman_utama/base/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body>
	<!--
  <nav class="navbar navbar-expand-md bg-primary navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="halaman_awal_donatur.html">
        <b>SIMBION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav" style="opacity: 1;">
          <li class="nav-item" id="tab-pengumuman">
            <a class="nav-link" href="halaman_awal_donatur.html#pengumuman_halaman_awal">Pengumuman</a>
          </li>
          <li class="nav-item" id="tab-list-beasis">
            <a class="nav-link" href="halaman_awal_donatur.html#beasiswa_halaman_utama" id="tab-list-beasis">List Beasiswa</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kegiatan</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="List_beasiswa.html">Lihat Beasiswa Anda</a>
              <a class="dropdown-item" href="membuat_paket_beasiswa_baru.html">Membuat Paket Beasiswa Baru</a>
              <a class="dropdown-item" href="membuat_pendaftaran_beasiswa_dari_paket.html">Menambahkan Beasiswa dari Paket</a>
              <a class="dropdown-item" href="#">Membuat Pengumuman</a>
            </div>
          </li>
        </ul>
        <a class="btn navbar-btn ml-2 text-white btn-danger" href="Login.html">
          <i class="fa d-inline fa-lg fa-user-circle-o"></i>Logout</a>
      </div>
    </div>
  </nav>
-->
  <div class="py-5 opaque-overlay bg-light text-dark">
    <div class="container">
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
          <h1 class="text-gray-dark">FORM PENDAFTARAN TAMBAH BEASISWA DARI PAKET</h1>
          <form class="" method="post" action="{% url 'daftarbeasiswa:registrasi_beasiswa' %}">
            {% csrf_token %}
            <div class="form-group">
              <label>Kode Beasiswa</label>
              <br>
              <select name='kodebeasiswa'>
                  {% for skema in skemabeasiswa %}
                    <option value = '{{ skema.kode }}'> {{ skema.kode }} </option>
                  {% endfor %}
              </select>
            </div>

            <div class="form-group">
              <label>No Urut</label>
              <input type="text" name="no_urut" class="form-control"> </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Tanggal Mulai Pendaftaran</label>
              <input name = "tanggal_mulai" type="date" class="form-control" id="inlineFormInput" placeholder="Jane Doe"> </div>

            <div class="form-group">
              <label for="exampleInputEmail1">Tanggal Tutup Pendaftaran</label>
              <input name = "tanggal_selesai" type="date" class="form-control" id="inlineFormInput"> </div>

            <button type="submit" class="btn btn-primary">Send</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

{% endblock %}