SIMBION20/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_utama.urls as halaman_utama
import login.urls as login
import register.urls as register
import daftarbeasiswa.urls as daftarbeasiswa


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(halaman_utama, namespace='halaman_utama')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^register/', include(register, namespace='register')),
    url(r'^daftarbeasiswa/', include(daftarbeasiswa, namespace='daftarbeasiswa')),
]

login/urls.py
from django.conf.urls import url
from .views import login
from .custom_auth import auth_login, auth_logout
#url for app
urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout'),
]

register/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^registrasi-mahaisiswa/', registrasi_mahasiswa, name='registrasi_mahasiswa'),
    url(r'^registrasi-donatur-individual/', registrasi_donatur_individual, name='registrasi_donatur_individual'),
    url(r'^registrasi-donatur-yayasan/', registrasi_donatur_yayasan, name='registrasi_donatur_yayasan'),
    url(r'^registrasi-validate-username/', validate_username, name='validate_username'),
    url(r'^registrasi-validate-no-identitas/', validate_no_identitas, name='validate_no_identitas'),
    url(r'^registrasi-validate-mahasiswa/', validate_mahasiswa, name='validate_mahasiswa'),
    url(r'^registrasi-validate-individu/', validate_individu, name='validate_individu'),
    url(r'^registrasi-validate-yayasan/', validate_yayasan, name='validate_yayasan')
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# Create your views here.
response = {}
def login(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('halaman_utama:index'))
    else:
        response['is_login'] = False
        html = 'login/login.html'
        return render(request, html, response)

login/templates/login/login.html
{% extends "halaman_utama/base/base.html" %}
{% load staticfiles %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-3"> </div>
        <div class="col-md-6">
          <div class="card text-white p-5 bg-primary">
            <div class="card-body">
              <h1 class="mb-4">Login</h1>
              <form action="{% url 'login:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Username </label>
                    <input type="text" class="form-control" id="username" name="username" required="required">
                </p>
                <p>
                    <label for="password"> Password </label>
                    <input type="password" class="form-control" id="password" name="password" required="required">
                </p>
                <input type="submit" id="submit" class="btn btn-secondary" value="login">
              </form>
              {% if wrong_account == True %}
                <p id="wrong_account" style="color: red">Username not registered please re-enter your username</p>
              {% elif wrong_password == True %}
                <p id="wrong_account" style="color: red">wrong password, please re-enter it</p>
              {% endif %}
              <p class="lead">Doesn't have an account yet? Register now!</p>
              <a href='{% url "register:index" %}' class="btn btn-secondary">
                <i class="fa d-inline fa-lg fa-user-circle-o"></i> Register </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}