SIMBION20/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import halaman_utama.urls as halaman_utama
import login.urls as login
import register.urls as register
import daftarbeasiswa.urls as daftarbeasiswa


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(halaman_utama, namespace='halaman_utama')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^register/', include(register, namespace='register')),
    url(r'^daftarbeasiswa/', include(daftarbeasiswa, namespace='daftarbeasiswa')),
]

daftarbeasiswa/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    #url(r'^$', login, name='login'),
    url(r'^pendaftaranpaket/$', pendaftaranpaket, name='pendaftaranpaket'),
    url(r'^tambahbeasiswa/$', tambahbeasiswa, name='tambahbeasiswa'),
    url(r'^registrasi_paket/$', registrasi_paket, name='registrasi_paket'),
    url(r'^registrasi_beasiswa/$', registrasi_beasiswa, name='registrasi_beasiswa'),
    #url(r'^auth_logout/$', auth_logout, name='auth_logout'),
]

halaman_utama/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

login/urls.py
from django.conf.urls import url
from .views import login
from .custom_auth import auth_login, auth_logout
#url for app
urlpatterns = [
    url(r'^$', login, name='login'),
    url(r'^auth_login/$', auth_login, name='auth_login'),
    url(r'^auth_logout/$', auth_logout, name='auth_logout'),
]

halaman_utama/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models

class Pengguna(models.Model):
    username = models.CharField(primary_key=True, max_length=20)
    password = models.CharField(max_length=20)
    role = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pengguna'

class Donatur(models.Model):
    nomor_identitas = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    npwp = models.CharField(max_length=20)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat = models.CharField(max_length=50)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'donatur'

class Admin(models.Model):
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username', primary_key=True)

    class Meta:
        managed = False
        db_table = 'admin'

class IndividualDonor(models.Model):
    nik = models.CharField(primary_key=True, max_length=16)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'individual_donor'

class Yayasan(models.Model):
    no_sk_yayasan = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp_cp = models.CharField(max_length=20, blank=True, null=True)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'yayasan'

class Mahasiswa(models.Model):
    npm = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp = models.CharField(max_length=20, blank=True, null=True)
    alamat_tinggal = models.CharField(max_length=50)
    alamat_domisili = models.CharField(max_length=50)
    nama_bank = models.CharField(max_length=50)
    no_rekening = models.CharField(max_length=20)
    nama_pemilik = models.CharField(max_length=20)
    username = models.ForeignKey('Pengguna', models.DO_NOTHING, db_column='username')

    class Meta:
        managed = False
        db_table = 'mahasiswa'

class RiwayatAkademik(models.Model):
    no_urut = models.IntegerField(primary_key=True)
    npm = models.CharField(max_length=20)
    semester = models.CharField(max_length=1)
    tahun_ajaran = models.CharField(max_length=9)
    jumlah_sks = models.IntegerField()
    ips = models.FloatField()
    lampiran = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'riwayat_akademik'
        unique_together = (('no_urut', 'npm'),)

class SkemaBeasiswa(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    jenis = models.CharField(max_length=20)
    deskripsi = models.CharField(max_length=50)
    nomor_identitas_donatur = models.ForeignKey(Donatur, models.DO_NOTHING, db_column='nomor_identitas_donatur')

    class Meta:
        managed = False
        db_table = 'skema_beasiswa'

class SyaratBeasiswa(models.Model):
    kode_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_beasiswa', primary_key=True)
    syarat = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'syarat_beasiswa'
        unique_together = (('kode_beasiswa', 'syarat'),)

class SkemaBeasiswaAktif(models.Model):
    kode_skema_beasiswa = models.ForeignKey(SkemaBeasiswa, models.DO_NOTHING, db_column='kode_skema_beasiswa', primary_key=True)
    no_urut = models.IntegerField()
    tgl_mulai_pendaftaran = models.DateField()
    tgl_tutup_pendaftaran = models.DateField()
    periode_penerimaan = models.CharField(max_length=50)
    status = models.CharField(max_length=20)
    jumlah_pendaftar = models.IntegerField()
    total_pembayaran = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'skema_beasiswa_aktif'
        unique_together = (('kode_skema_beasiswa', 'no_urut'),)

class Pendaftaran(models.Model):
    no_urut = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='no_urut', primary_key=True)
    kode_skema_beasiswa = models.IntegerField()
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    waktu_daftar = models.DateTimeField()
    status_daftar = models.CharField(max_length=20)
    status_terima = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'pendaftaran'
        unique_together = (('no_urut', 'kode_skema_beasiswa', 'npm'),)

class Pembayaran(models.Model):
    urutan = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='kode_skema_beasiswa')
    no_urut_skema_beasiswa_aktif = models.IntegerField()
    npm = models.ForeignKey(Mahasiswa, models.DO_NOTHING, db_column='npm')
    keterangan = models.CharField(max_length=50)
    tgl_bayar = models.DateField()
    nominal = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'pembayaran'
        unique_together = (('urutan', 'kode_skema_beasiswa', 'no_urut_skema_beasiswa_aktif'),)

class TempatWawancara(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    lokasi = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tempat_wawancara'

class Wawancara(models.Model):
    no_urut_skema_beasiswa_aktif = models.IntegerField(primary_key=True)
    kode_skema_beasiswa = models.ForeignKey(SkemaBeasiswaAktif, models.DO_NOTHING, db_column='kode_skema_beasiswa')
    jadwal = models.DateTimeField()
    kode_tempat_wawancara = models.ForeignKey(TempatWawancara, models.DO_NOTHING, db_column='kode_tempat_wawancara')

    class Meta:
        managed = False
        db_table = 'wawancara'
        unique_together = (('no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'jadwal'),)

class Pengumuman(models.Model):
    tanggal = models.DateField(primary_key=True)
    no_urut_skema_beasiswa_aktif = models.IntegerField()
    kode_skema_beasiswa = models.ForeignKey('SkemaBeasiswaAktif', models.DO_NOTHING, db_column='kode_skema_beasiswa')
    username = models.ForeignKey(Pengguna, models.DO_NOTHING, db_column='username')
    judul = models.CharField(max_length=20)
    isi = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'pengumuman'
        unique_together = (('tanggal', 'no_urut_skema_beasiswa_aktif', 'kode_skema_beasiswa', 'username'),)

halaman_utama/views.py
from django.shortcuts import render
from datetime import datetime, date
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.forms.models import model_to_dict
from .models import Pengumuman, SkemaBeasiswaAktif, SyaratBeasiswa
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]
# Create your views here.
response = {}

def index(request):
    print ("#==> masuk index")

    # Untuk masukin pengumuman ke halaman utama
    pengumuman = Pengumuman.objects.raw('SELECT * FROM pengumuman ORDER BY tanggal DESC')
    dict_pengumuman = []
    ii = 0
    for p in pengumuman:
        dictio = model_to_dict(p)
        dictio["id"] = ii
        dict_pengumuman.append(dictio)
        ii += 1
    pengumuman_list_for_pagination = dict_pengumuman
    paginator = Paginator(pengumuman_list_for_pagination, 2)
    page = request.GET.get('pengumuman_page')
    try:
        all_pengumuman = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        all_pengumuman = paginator.page(1)
    response["all_pengumuman"] = all_pengumuman

    # Untuk masukin beasiswa aktif ke halaman utama
    get_beasiswa_aktif = connection.cursor()
    get_beasiswa_aktif.execute('''      SELECT * 
                                        FROM skema_beasiswa_aktif, skema_beasiswa 
                                        WHERE kode_skema_beasiswa = kode
                                        ORDER BY tgl_tutup_pendaftaran ASC''')
    dict_beasiswa_aktif = dictfetchall(get_beasiswa_aktif)
    print(dict_beasiswa_aktif)
    jj = 1
    for p in dict_beasiswa_aktif:
        p["id"] = jj
        jj += 1
    beasiswa_aktif_list_for_pagination = dict_beasiswa_aktif
    paginator = Paginator(beasiswa_aktif_list_for_pagination, 3)
    page = request.GET.get('beasiswa_aktif_page')
    try:
        all_beasiswa_aktif = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        all_beasiswa_aktif = paginator.page(1)
    response["all_beasiswa_aktif"] = all_beasiswa_aktif

    # define html yang mau di render
    html = 'halaman_utama/halaman_utama.html'

    # check ada yang login atau enggak
    if 'user_login' in request.session:
        response['is_login'] = True
        response['role'] = request.session['role']
        print(response['role'])
        return render(request, html, response)

    else:
        response['is_login'] = False
        response['role'] = ""
        return render(request, html, response)

    

halaman_utama/templates/halaman_utama/base/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/theme.css' %}" type="text/css"> </head>

<body>

  <header>
    <nav class="navbar navbar-expand-md bg-primary navbar-dark">
      <div class="container">
        <a class="navbar-brand" href='{% url "halaman_utama:index" %}'>
          <b>SIMBION</b>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% if role == "mahasiswa" %}
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav" style="opacity: 1;">
            <li class="nav-item" id="tab-pengumuman">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#pengumuman_halaman_awal">Pengumuman</a>
            </li>
            <li class="nav-item" id="tab-list-beasis">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#beasiswa_halaman_utama" id="tab-list-beasis">List Beasiswa</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kegiatan</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Lihat Status Beasiswa</a>
                <a class="dropdown-item" href="#">Daftar Beasiswa</a>
                <a class="dropdown-item" href="#">Lihat Hasil Seleksi Beasiswa</a>
              </div>
            </li>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href='{% url "login:auth_logout" %}'>
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>Logout</a>
        </div>
      </div>
    </nav> 
        {% elif role == "donatur" %}
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav" style="opacity: 1;">
            <li class="nav-item" id="tab-pengumuman">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#pengumuman_halaman_awal">Pengumuman</a>
            </li>
            <li class="nav-item" id="tab-list-beasis">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#beasiswa_halaman_utama" id="tab-list-beasis">List Beasiswa</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kegiatan</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="List_beasiswa.html">Lihat Beasiswa Anda</a>
                <a class="dropdown-item" href='{% url "daftarbeasiswa:pendaftaranpaket" %}'>Membuat Paket Beasiswa Baru</a>
                <a class="dropdown-item" href='{% url "daftarbeasiswa:tambahbeasiswa" %}'>Menambahkan Beasiswa dari Paket</a>
                <a class="dropdown-item" href="#">Membuat Pengumuman</a>
              </div>
            </li>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href='{% url "login:auth_logout" %}'>
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>Logout</a>
        </div>
      </div>
    </nav>

        {% elif role == "admin" %}
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav" style="opacity: 1;">
            <li class="nav-item" id="tab-pengumuman">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#pengumuman_halaman_awal">Pengumuman</a>
            </li>
            <li class="nav-item" id="tab-list-beasis">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#beasiswa_halaman_utama" id="tab-list-beasis">List Beasiswa</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kegiatan</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Lihat Tempat Wawancara</a>
                <a class="dropdown-item" href="#">Membuat Tempat Wawancara</a>
                <a class="dropdown-item" href="#">Membuat Pengumuman</a>
              </div>
            </li>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-danger" href='{% url "login:auth_logout" %}'>
            <i class="fa d-inline fa-lg fa-user-circle-o"></i>Logout</a>
        </div>
      </div>
    </nav>

        {% else %}
        <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item" id="tab-pengumuman">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#pengumuman_halaman_awal">Pengumuman</a>
            </li>
            <li class="nav-item" id="tab-list-beasis">
              <a class="nav-link" href="{% url 'halaman_utama:index' %}#beasiswa_halaman_utama" id="tab-list-beasis">List Beasiswa</a>
            </li>
          </ul>
          <a class="btn navbar-btn ml-2 text-white btn-secondary" href='{% url "login:login" %}'>
            <i class="fa d-inline fa-lg fa-user-circle-o"></i> Sign in</a>
        </div>
      </div>
    </nav>
        {% endif %}   
  </header>

  {% block content %}
     <!-- content goes here -->
  {% endblock %}

  <footer>
    <div class="bg-dark text-white">
      <div class="container">
        <div class="row">
          <div class="p-4 col-md-3">
            <h2 class="mb-4 text-secondary">SIMBION</h2>
            <p class="text-white">A company for whatever you may need, from website prototyping to publishing</p>
          </div>
          <div class="p-4 col-md-3">
            <h2 class="mb-4 text-secondary">Mapsite</h2>
            <ul class="list-unstyled">
              <a href="#" class="text-white">Home</a>
              <br>
              <a href="#" class="text-white">About us</a>
              <br>
              <a href="#" class="text-white">Our services</a>
              <br>
              <a href="#" class="text-white">Stories</a>
            </ul>
          </div>
          <div class="p-4 col-md-3">
            <h2 class="mb-4">Contact</h2>
            <p>
              <a href="tel:+246 - 542 550 5462" class="text-white">
                <i class="fa d-inline mr-3 text-secondary fa-phone"></i>+246 - 542 550 5462</a>
            </p>
            <p>
              <a href="mailto:info@pingendo.com" class="text-white">
                <i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@pingendo.com</a>
            </p>
            <p>
              <a href="https://goo.gl/maps/AUq7b9W7yYJ2" class="text-white" target="_blank">
                <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>365 Park Street, NY</a>
            </p>
          </div>
          <div class="p-4 col-md-3">
            <h2 class="mb-4 text-light">Subscribe</h2>
            <form>
              <fieldset class="form-group text-white">
                <label for="exampleInputEmail1">Get our newsletter</label>
                <input type="email" class="form-control" placeholder="Enter email"> </fieldset>
              <button type="submit" class="btn btn-outline-secondary">Submit</button>
            </form>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 mt-3">
            <p class="text-center text-white">© Copyright Kelompok 20 Basis Data B - All rights reserved. </p>
          </div>
        </div>
      </div>
    </div>    
  </footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  {% block javascript %}
     <!-- content goes here -->
  {% endblock %}

</body>

</html>